import { STATUS_LABELS } from "./constants.js";
import { formatDate, escapeHtml, memberFor, projectFor, relativeDeadline, statusBadge } from "./formatters.js";
import { qs } from "./app.js";

export async function render(ctx) {
  let cursor = new Date(); cursor.setDate(1); let selected = new Date();
  const draw = () => {
    const year = cursor.getFullYear(); const month = cursor.getMonth(); const first = new Date(year, month, 1); const last = new Date(year, month + 1, 0); const offset = (first.getDay() + 6) % 7; const cells = [];
    for (let index = 0; index < offset; index += 1) { const date = new Date(year, month, index - offset + 1); cells.push({ date, outside: true }); }
    for (let day = 1; day <= last.getDate(); day += 1) cells.push({ date: new Date(year, month, day), outside: false });
    while (cells.length % 7) { const date = new Date(year, month, last.getDate() + cells.length - offset - last.getDate() + 1); cells.push({ date, outside: true }); }
    const todayKey = new Date().toISOString().slice(0, 10); const selectedKey = selected.toISOString().slice(0, 10); const byDate = new Map(); ctx.tasks.forEach((task) => { if (!task.deadline_at && !task.deadline) return; const key = (task.deadline_at || task.deadline).slice(0, 10); if (!byDate.has(key)) byDate.set(key, []); byDate.get(key).push(task); });
    const calendar = `<div class="cal-grid">${["จันทร์","อังคาร","พุธ","พฤหัส","ศุกร์","เสาร์","อาทิตย์"].map((day) => `<div class="cal-dow">${day}</div>`).join("")}${cells.map(({ date, outside }) => { const key = date.toISOString().slice(0, 10); const rows = byDate.get(key) || []; const conflict = rows.length > 1; return `<button class="cal-cell ${outside ? "is-outside" : ""} ${key === todayKey ? "is-today" : ""} ${key === selectedKey ? "is-selected" : ""} ${conflict ? "has-conflict" : ""}" data-date="${key}"><div class="cal-day"><span>${date.getDate()}</span>${rows.length ? `<span class="count">${rows.length}</span>` : ""}</div>${rows.slice(0, 2).map((task) => `<div class="cal-item ${relativeDeadline(task.deadline_at || task.deadline).className} ${task.status === "completed" ? "is-done" : ""}">${escapeHtml(task.title)}</div>`).join("")}${rows.length > 2 ? `<div class="cal-more">+${rows.length - 2} งาน</div>` : ""}</button>`; }).join("")}</div>`;
    const selectedRows = byDate.get(selectedKey) || [];
    const conflicts = [...byDate.entries()].filter(([, rows]) => rows.length > 1).sort(([a], [b]) => a.localeCompare(b)).slice(0, 6);
    qs("#page-content").innerHTML = `<div class="page-header"><div><h2>ปฏิทิน Deadline</h2><p class="page-desc">กำหนดส่งจากข้อมูล Task ใน database — คลิกวันที่เพื่อดูงานของวันนั้น</p></div><div class="row-wrap"><button class="btn" id="prev-month">← เดือนก่อน</button><span class="chip" style="min-width:150px;justify-content:center">${new Intl.DateTimeFormat("th-TH", { month: "long", year: "numeric" }).format(cursor)}</span><button class="btn" id="next-month">เดือนถัดไป →</button></div></div><div class="dashboard-grid"><section class="card card-flush"><div style="padding:14px 16px;border-bottom:1px solid var(--line)" class="row-between"><div class="card-title">${new Intl.DateTimeFormat("th-TH", { month: "long", year: "numeric" }).format(cursor)}</div><span class="text-xs text-muted">${ctx.tasks.filter((task) => task.status !== "completed").length} Active tasks</span></div><div style="padding:14px">${calendar}</div></section><aside class="stack"><section class="card"><div class="card-header"><div><div class="card-title">งานวันที่ ${formatDate(selectedKey)}</div><div class="card-sub">${selectedRows.length} งาน</div></div></div>${selectedRows.length ? selectedRows.map((task) => `<a class="list-item" style="padding-left:0;padding-right:0" href="task.html?id=${encodeURIComponent(task.id)}"><div class="list-item-main"><div class="list-item-title">${escapeHtml(task.title)}</div><div class="list-item-sub">${escapeHtml(projectFor(task, ctx.projects)?.name || "—")} · ${escapeHtml(memberFor(task, ctx.members)?.name || "—")}</div></div>${statusBadge(task.status)}</a>`).join("") : `<div class="state" style="padding:24px">ไม่มีงานในวันที่เลือก</div>`}</section><section class="card"><div class="card-header"><div class="card-title">Deadline Conflict</div><span class="badge ${conflicts.length ? "badge-warn" : "badge-ok"}">${conflicts.length ? `${conflicts.length} จุด` : "ไม่มี"}</span></div>${conflicts.length ? `<div class="conflict-list">${conflicts.map(([date, rows]) => `<div class="conflict"><strong>${formatDate(date)}</strong> · ${rows.length} งานชนกัน<br>${rows.map((task) => escapeHtml(task.title)).join(" · ")}</div>`).join("")}</div>` : `<div class="text-sm text-muted">ยังไม่มีงานหลายชิ้นที่ชน Deadline เดียวกัน</div>`}</section></aside></div>`;
    qs("#prev-month").addEventListener("click", () => { cursor = new Date(year, month - 1, 1); draw(); }); qs("#next-month").addEventListener("click", () => { cursor = new Date(year, month + 1, 1); draw(); }); document.querySelectorAll("[data-date]").forEach((cell) => cell.addEventListener("click", () => { selected = new Date(`${cell.dataset.date}T12:00:00`); draw(); }));
  }; draw();
}
