import { taskCard } from "./formatters.js";
import { formatDate, formatDateLong, relativeDeadline, workloadInfo, avatar, escapeHtml, roleLabel, memberFor, projectFor } from "./formatters.js";
import { STATUS_LABELS, STATUS_ORDER, workloadState } from "./constants.js";
import { qs, toast } from "./app.js";
import { openCreateTask, bindTaskCards } from "./task-actions.js";

export async function render(ctx) {
  const { tasks, members, projects, subtasks } = ctx;
  window.openCreateTask = () => openCreateTask(ctx);
  const active = tasks.filter((task) => task.status !== "completed");
  const dueSoon = tasks.filter((task) => task.status !== "completed" && relativeDeadline(task.deadline).className);
  const review = tasks.filter((task) => task.status === "review");
  const completed = tasks.filter((task) => task.status === "completed");
  const myTasks = tasks.filter((task) => task.assignee_id === ctx.member.id && task.status !== "completed");
  const teamLoad = members.map((member) => ({ member, info: workloadInfo(active.filter((task) => task.assignee_id === member.id), member.capacity_points) }));
  const avg = teamLoad.length ? Math.round(teamLoad.reduce((sum, item) => sum + item.info.percent, 0) / teamLoad.length) : 0;
  const critical = teamLoad.filter((item) => item.info.percent >= 80).length;
  const answerCards = `<div class="answer-grid"><div class="answer"><div class="q">วันนี้มีงานอะไร?</div><div class="a">${myTasks.length} งานของคุณกำลังเดินอยู่</div></div><div class="answer"><div class="q">งานไหนใกล้ Deadline?</div><div class="a">${dueSoon.length} งานต้องจับตา</div></div><div class="answer"><div class="q">งานอยู่ขั้นตอนไหน?</div><div class="a">${review.length} งานกำลังรอคอมเมนต์</div></div><div class="answer"><div class="q">ใครมี Workload สูง?</div><div class="a">${critical ? `${critical} คนต้องช่วยจัดสรร` : "ยังไม่มีคนเกินเกณฑ์"}</div></div></div>`;
  const activity = active.slice(0, 5).map((task) => { const member = memberFor(task, members); return `<div class="activity-item"><div class="activity-dot" style="background:${task.status === "review" ? "var(--warn)" : task.status === "revision" ? "var(--danger)" : "var(--kkp-purple)"}"></div><div class="activity-main"><div class="activity-name">${escapeHtml(member?.name || "ไม่ระบุ")} <span class="text-muted" style="font-weight:400">กำลังทำ</span></div><div class="activity-task">${escapeHtml(task.title)} · ${escapeHtml(STATUS_LABELS[task.status])}</div></div><div class="activity-right"><div class="text-xs text-muted">${Number(task.workload_points)} pts</div><div class="text-xs text-muted">${formatDate(task.deadline)}</div></div></div>`; }).join("");
  const deadlines = [...tasks].filter((task) => task.status !== "completed").sort((a, b) => String(a.deadline).localeCompare(String(b.deadline))).slice(0, 5).map((task) => { const project = projectFor(task, projects); const member = memberFor(task, members); const date = task.deadline ? new Date(`${task.deadline}T12:00:00`) : null; return `<div class="deadline-item"><div class="deadline-date"><span class="day">${date ? date.getDate() : "—"}</span><span class="month">${date ? date.toLocaleDateString("en-US", { month: "short" }) : "—"}</span></div><div class="deadline-main"><div class="deadline-title">${escapeHtml(task.title)}</div><div class="deadline-sub">${escapeHtml(project?.name || "—")} · ${escapeHtml(member?.name || "—")}</div></div><span class="badge ${relativeDeadline(task.deadline).className === "is-overdue" ? "badge-danger" : relativeDeadline(task.deadline).className ? "badge-warn" : "badge-neutral"}">${escapeHtml(relativeDeadline(task.deadline).label)}</span></div>`; }).join("");
  const loadRows = teamLoad.map(({ member }) => { const memberTasks = active.filter((task) => task.assignee_id === member.id); const reviewTasks = memberTasks.filter((task) => ["review", "revision"].includes(task.status)).length; const doneTasks = tasks.filter((task) => task.assignee_id === member.id && task.status === "completed").length; return `<div class="team-mini"><div>${avatar(member, "avatar-sm")}</div><div class="team-mini-main"><div class="team-mini-name">${escapeHtml(member.name)}</div><div class="team-mini-meta">${escapeHtml(roleLabel(member.role))} · ${memberTasks.length} งานกำลังทำ · ${doneTasks} งานเสร็จแล้ว</div></div><div class="chip">${reviewTasks} งานรอรีวิว</div></div>`; }).join("");
  const urgentCards = dueSoon.slice(0, 3).map((task) => taskCard(task, { projects, members, subtasks })).join("");
  qs("#page-content").innerHTML = `<div class="page-header"><div><h2>วันนี้ทีมกำลังขยับงานอะไรอยู่</h2><p class="page-desc">ภาพรวม workflow, deadline และภาระงานของทีมในจุดเดียว</p></div><div class="row-wrap"><span class="chip">อัปเดตล่าสุด ${new Intl.DateTimeFormat("th-TH", { hour: "2-digit", minute: "2-digit" }).format(new Date())}</span><button class="btn btn-primary" id="dashboard-create">＋ สร้างงานใหม่</button></div></div>${answerCards}<section class="section" style="margin-top:18px"><div class="stat-grid"><div class="stat is-primary"><div class="stat-label">งานทั้งหมด</div><div class="stat-value">${tasks.length}</div><div class="stat-hint">ทั้ง Active และ History</div></div><div class="stat is-info"><div class="stat-label">กำลังทำ</div><div class="stat-value">${active.length}</div><div class="stat-hint">ยังอยู่ใน workflow</div></div><div class="stat is-warn"><div class="stat-label">รอคอมเมนต์</div><div class="stat-value">${review.length}</div><div class="stat-hint">ต้องการการตัดสินใจ</div></div><div class="stat is-danger"><div class="stat-label">ใกล้ Deadline</div><div class="stat-value">${dueSoon.length}</div><div class="stat-hint">ภายใน 2 วัน / เลยกำหนด</div></div><div class="stat is-ok"><div class="stat-label">เสร็จแล้ว</div><div class="stat-value">${completed.length}</div><div class="stat-hint">อยู่ใน Work History</div></div></div></section><div class="dashboard-grid"><section class="card"><div class="card-header"><div><div class="card-title">Current Team Activity</div><div class="card-sub">ใครกำลังทำอะไรอยู่ตอนนี้</div></div><a class="btn btn-ghost btn-sm" href="team.html">ดูทีมทั้งหมด →</a></div>${activity || `<div class="state">ยังไม่มีงานกำลังทำ</div>`}</section><section class="card"><div class="card-header"><div><div class="card-title">Upcoming Deadline</div><div class="card-sub">งานที่ควรจับตาเป็นลำดับแรก</div></div><a class="btn btn-ghost btn-sm" href="calendar.html">เปิดปฏิทิน →</a></div>${deadlines || `<div class="state">ยังไม่มี deadline</div>`}</section></div><div class="dashboard-grid" style="margin-top:16px"><section class="card"><div class="card-header"><div><div class="card-title">สรุปงานรายคน</div><div class="card-sub">จำนวนงานที่กำลังทำ งานรอรีวิว และงานที่เสร็จแล้ว</div></div><a class="btn btn-ghost btn-sm" href="team.html">จัดสรรงาน →</a></div>${loadRows}</section><section class="card"><div class="card-header"><div><div class="card-title">งานที่ต้องขยับเร็ว</div><div class="card-sub">งานใกล้กำหนดและงานที่กำลังติด review</div></div><a class="btn btn-ghost btn-sm" href="board.html">เปิด Board →</a></div><div class="task-grid" style="grid-template-columns:1fr">${urgentCards || `<div class="state">ยังไม่มีงานเร่งด่วน</div>`}</div></section></div>`;
  qs("#dashboard-create")?.addEventListener("click", () => openCreateTask(ctx));
  bindTaskCards(qs("#page-content"));
}
