import { avatar, escapeHtml, roleLabel, projectFor, formatDate, relativeDeadline, taskTypeLabel } from "./formatters.js";
import { qs } from "./app.js";
import { STATUS_LABELS } from "./constants.js";

export async function render(ctx) {
  const tasks = Array.isArray(ctx.tasks) ? ctx.tasks : [];
  const members = Array.isArray(ctx.members) ? ctx.members : [];
  const projects = Array.isArray(ctx.projects) ? ctx.projects : [];
  const active = tasks.filter((task) => task.status !== "completed");
  const late = active.filter((task) => relativeDeadline(task.deadline_at || task.deadline).className === "is-overdue");
  const memberCards = members.map((member) => {
    const memberTasks = tasks.filter((task) => task.assignee_id === member.id);
    const activeTasks = memberTasks.filter((task) => task.status !== "completed");
    const projectsForMember = [...new Map(activeTasks.map((task) => { const project = projectFor(task, projects); return [project?.id, project]; }).filter(([, project]) => project)).values()];
    const statusCount = (status) => activeTasks.filter((task) => task.status === status).length;
    return `<section class="member-card"><div class="member-head">${avatar(member, "avatar-lg")}<div><div class="member-name">${escapeHtml(member.name)}</div><div class="member-role">${escapeHtml(roleLabel(member.role))}</div></div><span class="spacer"></span><span class="chip">${activeTasks.length} งานกำลังทำ</span></div><div class="member-metrics"><div class="metric"><div class="k">รอรับบรีฟ</div><div class="v">${statusCount("brief")}</div></div><div class="metric"><div class="k">กำลังดราฟต์</div><div class="v">${statusCount("drafting")}</div></div><div class="metric"><div class="k">รอรีวิว / แก้ไข</div><div class="v">${statusCount("review") + statusCount("revision")}</div></div><div class="metric"><div class="k">เสร็จแล้วทั้งหมด</div><div class="v">${memberTasks.filter((task) => task.status === "completed").length}</div></div></div><div class="summary-line"><span class="text-xs text-muted">สรุปงานของ ${escapeHtml(member.name)}</span><strong class="text-sm">${activeTasks.length ? `${activeTasks.reduce((sum, task) => sum + Number(task.item_count || 1), 0)} ชิ้นงานที่กำลังเดินอยู่` : "ยังไม่มีงานที่กำลังทำ"}</strong></div><div><div class="text-xs text-muted" style="margin-bottom:5px">รายการงาน</div>${memberTasks.length ? memberTasks.slice(0, 8).map((task) => { const due = relativeDeadline(task.deadline_at || task.deadline); return `<a class="list-item" style="padding:7px 0" href="task.html?id=${encodeURIComponent(task.id)}"><div class="list-item-main"><div class="list-item-title">${escapeHtml(task.title)} <span class="chip">${escapeHtml(taskTypeLabel(task.task_type))}</span></div><div class="list-item-sub">${escapeHtml(projectFor(task, projects)?.name || "—")} · ${Number(task.item_count || 1)} ชิ้น · ${formatDate(task.deadline_at || task.deadline)}</div></div><span class="badge ${due.className === "is-overdue" ? "badge-danger" : due.className === "is-due-soon" ? "badge-warn" : "badge-neutral"}">${escapeHtml(due.label)}</span></a>`; }).join("") : `<div class="text-sm text-muted">ยังไม่มีงาน</div>`}</div><div class="tag-list">${projectsForMember.length ? projectsForMember.map((project) => `<span class="chip">${escapeHtml(project.name)}</span>`).join("") : `<span class="text-xs text-muted">ยังไม่มี Active Project</span>`}</div></section>`;
  }).join("");
  qs("#page-content").innerHTML = `<div class="page-header"><div><h2>ทีม & สรุปงาน</h2><p class="page-desc">สรุปงานและจำนวนชิ้นงานของแต่ละคน โดยไม่ใช้คะแนน Workload หรือ Capacity</p></div><div class="row-wrap"><span class="chip">${members.length} สมาชิก</span><span class="chip">${active.length} งานกำลังทำ</span><span class="chip">${late.length} งานเลท</span></div></div><div class="grid grid-4" style="margin-bottom:16px"><div class="card"><div class="text-xs text-muted">สมาชิกในทีม</div><div class="report-number">${members.length} <small>คน</small></div></div><div class="card"><div class="text-xs text-muted">งานที่กำลังทำ</div><div class="report-number">${active.length} <small>งาน</small></div></div><div class="card"><div class="text-xs text-muted">จำนวนชิ้นงานที่กำลังทำ</div><div class="report-number">${active.reduce((sum, task) => sum + Number(task.item_count || 1), 0)} <small>ชิ้น</small></div></div><div class="card"><div class="text-xs text-muted">งานเลท</div><div class="report-number">${late.length} <small>งาน</small></div></div></div><div class="grid grid-2">${memberCards || `<div class="card"><div class="state"><div class="state-title">ยังไม่มีสมาชิกในทีม</div><div class="state-text">เพิ่มสมาชิกใน Supabase team_members ก่อน จึงจะแสดงสรุปงานรายคน</div></div></div>`}</div>`;
}
